// Package Types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package Types

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5yUwY4TMQyGXyUyHLvdIm5z5ATSLkKiSEiIg2fGMzUkTpR4KlarvjtKst3pdiqgnJo4",
	"sfP78995hM674IVEEzSPkLodOSxL2pNoXoToA0VlqmHp809PqYsclL1AA9sdGZLeKDsyfjCa9znfYDJf",
	"Pn74Wk6SoguwAn0IBA2wKI0U4bACLjWXcUFXX30daYAGXt3Ocm+ftN4mjSzjPYackRSjXhZYjv5T4uE5",
	"5Nsf1Gl+qmQXdazk/iqz8pwLYYz4kPcWZZxwpEp3ctB8g54gH8D3FdAvdMHmDIuzstp0Sfcd1i7PR4VW",
	"Wae+FB58dKjQwGA96lxHJtdW1ifAMstroL8Y36yM0z2yLIehcSLDdQRH9YZT2TtkMY5IWcabdmLb52LP",
	"clvvLaFUbNd0Z72MV1z3e4po7d0J2z/ROL+ep8xq6TqQl0x25PPvPrOnIs6sdqGto+PQeRJqp5hptxEn",
	"Gcimlwacwxd8ODeyMGKlvnQuXggvIeQQy+CXRnq/3X4yieKeohl8LAb6TEHZoaC5Q2VB8w67n/mj9TSS",
	"/NTxSgg3bT292anm//2eYqq1N+s3601hFkgwMDTwdr1Zb2AFAXWX+zocfgcAAP//tgE7Az8FAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.Swagger, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewSwaggerLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.SwaggerLoader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadSwaggerFromData(specData)
	if err != nil {
		return
	}
	return
}
