// Package Openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package Openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "SeptimanappBackend/openApi/types"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RUX2/UMAz/KpHhMWu74wX6OAnBxCQmtje0h9C6V0ObZImvXHXKd0dpae9Wjt2QYDxF",
	"UWzHvz/2DgrTWqNRs4d8FySQrgzkOyjRF44sk9GQw/vb22vh0XXoRGWc4BrFDVqmVmklrhSTVuJCFd9Q",
	"lyCBiRuEHPwUYu3Zl/H1rGa2IKFD58faWbJKMggSjEWtLEEOr5IsyUCCVVzHviDF7meLsEaOh7HoVOzu",
	"soQc3iG/HSNiklMtMjoP+eclEKrEmjrUwuimF2NVYSrBNXnRo3JCORQOeeM0RigUs+436HqQoFUbYcU4",
	"kOCLGlsVm8Gtam1EvMrO30ho1ZbaTRuvq0xCS3q6nr+WwL2NRUgzrtFBCHcSHHprtMcB4SrL4lEYzagH",
	"sMrahooBbvrVRyC7g99fOqwghySNlX3Sq7Z5ke51TcdIP3EYQpALVka8fpD1kBMUs4KD7KppRDyEt1hQ",
	"RcVA2VjRGn9EmGvj98o4vN+g5wtT9v8cYPyLHJaQs9tgOEkx45ZT2yha/D1LCx8/wCyeZ0d6fYzKG9Xh",
	"SGQkBEuxbyrIycfpjspw2syX5a92HvwY52JvRyphiffQnP/Xb8c4+rS0m/hOXA/XcTipnPhqzNjGo6N/",
	"NQc9E7J9V4+gi8OyCPyD1TRnztvJdOhU00xgn7KoFikPdtZTsS5rhHD3QJiTXp7V+at2nifw7pk1P2Xo",
	"Ke43ng7hRwAAAP//hkAqRnQHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "./types.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.Swagger, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewSwaggerLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.SwaggerLoader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadSwaggerFromData(specData)
	if err != nil {
		return
	}
	return
}
