// Package Openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package Openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "SeptimanappBackend/openApi/types"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RUy27bOhD9FWLuXSqW6u60a4CiNRKgQROgi8AoWGlsTSORDDlyoxr894KkLcfOwynQ",
	"piua1uFwzmO4hkp3RitU7KBcg8Oqt8TDZdVgh/EvacxXqsOvGl1lyTBpBSW8u5iJGxwEayF7brSlnygs",
	"3vbo2E0gAwqo2x7tABko2SGUoRjVkAEPJm3pDAfw3gf4Qj+85ePV1YVwaFdoxUJbwQ2KSzRMnVRSnEsm",
	"JcWprG5QxbrEbSjsthBjTr6lrycNs4EMVmhdql1MppMCfAbaoJKGoIS3k2JSQAZGchPZ57jaarNEDos2",
	"aGXoblZDCR+Q3ydEOGRlh4zWQXl9SIQWYkkrVEKrdhCpqtALwQ05MaC0QtqgH/dWYf2EfAEHGbjgjgzN",
	"4J3sTGA8LaZFBp28o67v4vZNBh2pcVuMopNiXKIF7+cZWHRGK5esnhZFWCqtGBVvzG+pinTz7y4QWd+7",
	"/X+LCyhhkofKbjLIrv0v3wUqT0i30fALcTOrk9n72iTWLpp7XxkUo4/RfNm2IizCGaxoQVUULlU02j1i",
	"z4V2O3824TzV9fAXaaZ2wl1ksYaSbY/+qNCMd5ybVtLB3aPB8OlsNzeOLanlY1JeyhUmIYMgWIuxqWwc",
	"7pjO7Vhfz/08fNx0n6+p9sfTPqsf5j0GNgzOLq9x1veluJ/efxvIp/P4+TCP4gdxE7dphikeC6q1OjXz",
	"7AtxPoJeid+uq2fYhWk6AP7GCzaeHB8xvUIr23ZL9iXv2cGRvaftpVwPa3g/3zPmaKJHd/5oqMcRnb+y",
	"58cCvcU9kWnvfwUAAP//oIEUZhQIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "./types.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.Swagger, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewSwaggerLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.SwaggerLoader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadSwaggerFromData(specData)
	if err != nil {
		return
	}
	return
}
