openapi: "3.0.0"
info:
  description: HTTP server for the Septimana Latina Backend

  title: septimanapp-backend-http

  version: 0.1.0

paths: {}

components:
  schemas:
    event:
      type: object
      properties:
        id:
          type: integer
        start:
          type: integer
          description: "The start time of the event as UNIX timestamp"
        end:
          type: integer
          description: "The end time of the event as UNIX timestamp"
        names:
          $ref: "#/components/schemas/stringMap"
          description: "Map containing a name/description of the event for given languages"
#        location:
#          type: string
#          description: "The location of the event"
    events:
      type: array
      items:
        $ref: "#/components/schemas/event"

    location:
      type: object
      properties:
        id:
          type: string
        overallLocation:
          $ref: "#/components/schemas/overallLocation"
          description: "The main city or place which the location belong to"
        longitude:
          type: number
          format: float
        latitude:
          type: number
          format: float
        altitude:
          type: number
          format: float
        isMain:
          type: boolean
          description: "true if the location is the main meeting-building"
        titleMap:
          $ref: "#/components/schemas/stringMap"
          description: "Map containing the title of the location for given languages"
        descriptionMap:
          $ref: "#/components/schemas/stringMap"
          description: "Map containing the description(if given) of the location for given languages"

    locations:
      type: array
      items:
        $ref: "#/components/schemas/location"

    language:
      type: string
      enum: [ "de", "la" ]
      example: "la"

    overallLocation:
      type: string
      enum: [ "amoeneburg", "braunfels" ]
      example: "braunfels"

    stringMap:
      type: object
      properties:
        la:
          type: string
        de:
          type: string